version: '3'
name: abot-stack

# PORTS
# - 5001

services:
  redis:
    container_name: redis
    image: redis
    restart: unless-stopped
    ports:
      - '6379:6379'
  abot-cli:
    container_name: abot-cli
    image: abot-cli
    pull_policy: never
    build: &abot-dockerfile
      context: ../.
      dockerfile: docker/Dockerfile.abot
    restart: unless-stopped
    environment:
      - ABOT_API_KEYS=justsomecoolapikey
      - ABOT_IBP_MONITOR_URL=http://localhost:30001
      - ABOT_MEMBERS_JSON_URL=https://raw.githubusercontent.com/ibp-network/config/main/members.json
      - ABOT_DATA_PATH=/data/
      - ABOT_MATRIX_PUBLIC_ROOM=ibp-alerts:matrix.org
      - ABOT_MATRIX_BOT_USER=@ibp-alerts-bot-account:matrix.org
      - ABOT_MATRIX_BOT_PASSWORD=anotthateasypassword
      - ABOT_API_HOST=127.0.0.1
      - ABOT_API_PORT=5001
      - ABOT_REDIS_HOSTNAME=redis:6379

    volumes:
      - ../tmp:/data
    ports:
      - '5001:5001'
    # command: |
    #   --debug
    #   --data-path /data